services:
  back:
    build:
      context: .
      dockerfile: apps/back/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db

  front:
    build:
      context: .
      dockerfile: apps/front/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/front/node_modules
    depends_on:
      - back

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
